gravita_admin_notification_list_item:
    resource: |
        alias: gravita.notification_list_item
        section: admin
        templates: "@SyliusAdminBundle/Crud"
        except: ['create', 'update']
        redirect: show
        grid: gravita_admin_notification_list_item
        vars:
            all:
                subheader: gravita.ui.notification_list_item.subheader # define a translation key for your entity subheader
            index:
                icon: 'file image outline' # choose an icon that will be displayed next to the subheader
    type: sylius.resource